####################
### local 
####################

server:
  port: 9800
  forward-headers-strategy: framework
  
spring: 
  datasource: 
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ENC(8ePNsf2H5S3VYxy8L5eju8m/YvGEHDOhTRi8XzDDzVzgpTSN2jO4ZxSUhjux2oJGYobLSxvmlW03Ys2VBeeoGiBHXne+CfH6Ld5j+pcut4Ec55pxA2ZfD1tTdbXRFvthJZZ5QNGXfiZwccuM6J6x3mvuZ9gYHQQe)  # dev
      username: ENC(veYh7ARI5EhE8/f+X2TBYA==)
      password: ENC(SFf/vt7ZT0dlZPZc4Zpoykc15LU0ipln)
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 10


## appinfo
app-info: 
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
    
## actuator
management: 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      
feign: 
  api: 
    auth: 
      name: onm-auth
      url: http://onm-auth.sksignet.com:8800

## Interface API Infos (AS-IS)
api: 
  credit:  
    nice:
      url: 211.33.136.19:4457
      header: 
        merchantGId: 23933002201280000001  
  alimtalk:  
      sendurl: https://jupiter.lunasoft.co.kr/api/AlimTalk/message/send 
      userid: homenservice
      apikey: 81eh0c8a8anlamd996ikqbmvd06goledpz7llt9q
     

## FTP Infos (AS-IS)
ftp: 
  sendurl: 210.116.112.170
  domainurl: https://hns.sksignet.com/fileserver
  basepath: /data/upload
  userid: root
  passwd: cpos!@34
   
    

jwt: 
  secret: "sksignet_onm_service"
  expiredTime: 3600000

token: 
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: "sksignet_onm_service"
  refresh-token-name: refresh-token
  access-token-name: access-token  
  