####################
### dev 
####################

server:
  port: 9800


#appinfo
app-info: 
  build:
    version: '0.0.1-SNAPSHOT'
    timestamp: '2022-11-02T01:17:35Z'
    
#actuator
management: 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
